{
    CONFIG_REGIONS: [
        "Languedoc-Roussillon"
    ],
    CONFIG_LOCATION_TITLES: [
        "Territoire",
        "Vignoble",
        "Département",
    ],
    CONFIG_LOCATIONS: [
        "Secteur",
        "Nord Aquitaine",
        "Sud Drôme",
        "Côtes du Rhône",
        "Vallée du Rhône",
        "Sud Luberon",
        "Bouches du Rhône",
        "Ste Victoire",
        "Provence",
        "Saône et Loire",
        "Côte d'Or",
        "Yonne",
        "Nièvre",
        "Franche Comté",
        "Aude",
        "Gard",
        "Hérault",
        "Pyrénées-Orientales",
        "Beaujolais",
        "Coteaux du Lyonnais",
        "Forez",
        "Roannais",
        "Côtes du Rhône nord",
        "Diois",
        "Savoie",
        "Bugey",
        "Balmes dauphinoises",
        "Sud Ardèche",
    ],
    CONFIG_STAGE_TITLES: [
        "stades végétatifs",
        "stades phénologiques",
        "phénologie",
    ],
    CONFIG_STAGES: [
        "stade",
        "baies",
        "fleur",
        "fermeture",
        "floraison",
        "nouaison",
        "grain",
        "récolte",
        "véraison",
    ],
    CONFIG_PESTS: [
        "Mildiou",
        "Oïdium",
        "Black-rot",
        "Blackrot",
        "Botrytis",
        "Pourriture grise",
        "Maladie du bois",
        "Excoriose",
        "Eutypiose",
        "Cicadelles FD",
        "Vers de la grappe",
        "Tordeuses",
        "Tordeuses de la grappe",
        "Eudémis",
        "Cochylis",
        "Pyrale",
        "Pyrale de la vigne",
        "Pyrale du Daphné",
        "Ephestia sp.",
        "Eulia",
        "Ephestia unicolorella",
        "Noctuelles",
        "Boarmies",
        "Mange bourgeons",
        "Mange-bourgeons",
        "Acariose",
        "Acariens",
        "Erinose",
        "Araignées rouges",
        "Cicadelle verte",
        "Cicadelle vectrice de la flavescenc",
        "Cicadelle de la flavescence dorée",
        "Flavescence dorée",
        "Cochenilles",
        "Escargots",
        "Nécrose bactérienne",
        "Thrips",
        "Cigarier",
        "Ephippigère",
        "Malacome du Portugal",
        "Cochenille floconneuse",
        "Metcalfa pruinosa",
        "Altise",
        "Petit hanneton de la vigne",
        "Punaise verte",
        "Drosophile",
        "Drosophila Suzukii",
    ],
}